import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./products/page";
import { ActiveLink } from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav>
					<ul className="flex justify-center space-x-4">
						<ActiveLink
							href="/"
							className="text-blue-400 hover:text-blue-600"
							activeClassName="underline"
							exact={true}
						>
							Home
						</ActiveLink>
						<ActiveLink
							href="/products"
							className="text-blue-400 hover:text-blue-600"
							activeClassName="underline"
							exact={false}
						>
							All
						</ActiveLink>
					</ul>
				</nav>
				<section className="mx-auto max-w-md p-12 sm:max-w-2xl sm:py-16 md:max-w-4xl lg:max-w-7xl">
					{children}
				</section>
				<footer className="text-center text-sm text-gray-500">
					<p>2023</p>
				</footer>
			</body>
		</html>
	);
}
